"""Stand alone script use for setup and clean the apps_raw into application_path.json"""

# Importing modules
from pathlib import Path
import json
import os

# Path and variables
parent_path = os.getcwd()
raw_path = Path(parent_path + r"\attachment\apps_raw.json")
final_output = Path(parent_path + r"\attachment\application_path.json")
new_json = {}

# Cleaning json data
def clean_json_data(application: list) -> dict:
    clean_json = {}
    count = 0

    # Looping through every path
    while True:
        try:
            current_apps = application[count]
            clean_json[current_apps["Name"]] = {
                "Name": current_apps["Name"],
                "ID": current_apps["AppID"]
            }
            count += 1
        except:
            break

    return clean_json


# Remove windows unused system application
def remove_unwanted_application(apps: dict) -> dict:
    filtered = {}

    # List of keywords to remove
    BLOCKLIST_KEYWORDS = [
        "help",
        "manual",
        "release notes",
        "what is new",
        "faq",
        "troubleshooter",
        "support center",
        "on the web",
        "docs",
        "manuals",
        "module docs",
        "python"
    ]

    # Define the path type
    def is_type_d(name: str, appid: str) -> bool:
        if appid.startswith("Microsoft.AutoGenerated."):
            return True
        if appid.endswith(".msc"):
            return True
        if any(k in name.lower() for k in [
            "policy",
            "monitor",
            "scheduler",
            "configuration",
            "diagnostic",
        ]):
            return True
        return False

    def is_user_irrelevant(name: str) -> bool:
        lname = name.lower()
        return any(k in lname for k in BLOCKLIST_KEYWORDS)

    # Looping throgh every path
    for key, app in apps.items():
        name = app["Name"]
        appid = app["ID"]

        if is_type_d(name, appid):
            continue

        if is_user_irrelevant(name):
            continue

        filtered[key] = app

    # Return the clean json
    print(f"✔ Saved {len(filtered)} user-ready apps")
    return filtered
    

# Adding aliassess to the cleaned json
def add_aliasess(data: dict) -> dict:
    final_json = {}
    for key, value in data.items():
        aliases = []
        if len(key.split()) > 1:
            aliases = [key]
            for i in range(1, len(key.split())):
                previous_key = i - 1
                word = " ".join(key.split()[previous_key:i+1])
                aliases.append(word)
                pass

            for word in key.split():
                aliases.append(word)
        else:
            if len(key) > 3:
                aliases = [key, key[0:3]]
            else:
                aliases = [key]
        data[key]["Aliasess"] = aliases
        final_json[key] = value
    return final_json


# Main script runner
if __name__ == "__main__":
    # Opening raw_application.json
    try:
        with raw_path.open(encoding="utf-8-sig") as f:
            apps = json.load(f)
    except:
        with raw_path.open(encoding="utf-16") as f:
            apps = json.load(f)

    # Proccessing the json file
    app_path = clean_json_data(apps)
    cleaned_json = remove_unwanted_application(app_path)
    final_json = add_aliasess(cleaned_json)

    # Saving final json file
    with final_output.open("w", encoding="utf-16") as f:
        json.dump(final_json, f, indent=2, ensure_ascii=False)
